export const SET_API_REQUEST = "SET_API_REQUEST";
export const SET_API_SUCCESS = "SET_API_SUCCESS";
export const GET_API_REQUEST = "GET_API_REQUEST";
export const GET_API_SUCCESS = "GET_API_SUCCESS";
